version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    container_name: backend-gacha-simulator
    command: npm run start:dev
    environment:
      - PORT=3000
      - URI_MONGO=mongodb://mongo:27017/gacha-simulator
      - DB_NAME=gacha-simulator
      - SECRET_JWT=PRUBEAA22
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    restart: 'no'

  mongo:
    image: mongo:latest
    container_name: mongodb-gacha
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=gacha-simulator
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'

volumes:
  mongo_data:
